version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "21:00"
  open-pull-requests-limit: 10
  reviewers:
  - fannheyward
  ignore:
  - dependency-name: got
    versions:
    - ">= 10.4.a, < 10.5"
  - dependency-name: eslint-config-prettier
    versions:
    - 8.0.0
