version: 2
updates:
- package-ecosystem: npm
  open-pull-requests-limit: 10
  directory: "/"
  schedule:
    interval: monthly
    time: "21:00"
  groups:
    dev-dependencies-tunnel:
      patterns:
      - "@types/tunnel"
      - "tunnel"
    dev-dependencies-semver:
      patterns:
      - "@types/semver"
      - "semver"
    dev-dependencies-node-fetch:
      patterns:
      - "@types/node-fetch"
      - "node-fetch"
    dev-dependencies-glob:
      patterns:
      - "@types/glob"
      - "glob"
  reviewers:
  - fannheyward
