version: 2
updates:
- package-ecosystem: npm
  open-pull-requests-limit: 10
  directory: "/"
  schedule:
    interval: monthly
    time: "21:00"
  open-pull-requests-limit: 10
  reviewers:
  - fannheyward
